# Generated by Django 5.1 on 2024-11-07 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeers', '0001_initial'),
        ('usercredintials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usercredintials.userdetails'),
            preserve_default=False,
        ),
    ]
