# Generated by Django 5.1 on 2024-11-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeers', '0002_employer_user'),
        ('usercredintials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('Sales', 'Sales'), ('Medical', 'Medical'), ('Marketing', 'Marketing')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usercredintials.userdetails')),
            ],
        ),
    ]
