# Generated by Django 5.1 on 2024-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0012_alter_personalinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
