# Generated by Django 5.1 on 2024-11-06 07:29

import usercredintials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20, validators=[usercredintials.models.validate_password_strength])),
                ('category', models.CharField(choices=[('Employer', 'Employer'), ('Jobseeker', 'Jobseeker')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
